from unitxt.catalog import add_to_catalog
from unitxt.metrics import (
    SQLExecutionAccuracy,
    SQLExecutionLogicAccuracy,
    SQLNonExecutionAccuracy,
)
from unitxt.test_utils.metrics import test_metric

sql_execution_accuracy_metric = SQLExecutionAccuracy()

predictions = [
    "SELECT nme FROM employees WHERE department = 'Sales'",
    "SELECT name FROM employees WHERE department = 'Sales'",
    "SELECT name FROM employees WHERE department = 'Engineering'",
    "SELECT id, name FROM employees WHERE department = 'Sales'",
    "SELECT name FROM employees WHERE department = 'Non-Existent'",
    "Garbage SELECT * FROM",
    "SELECT name FROM employees ORDER BY salary ASC;",
    "Here is a SQL query: SELECT name FROM employees ORDER BY salary DESC; It's a good one!",
]  # Incorrect column name 'nme'
references = [
    ["SELECT name FROM employees WHERE department = 'Sales';"],
    ["SELECT name FROM employees WHERE department = 'Sales';"],
    ["SELECT name FROM employees WHERE department = 'Sales';"],
    ["SELECT name FROM employees WHERE department = 'Sales';"],
    ["SELECT name FROM employees WHERE department = 'Non-Existent';"],
    ["SELECT name FROM employees WHERE department = 'Sales';"],
    ["SELECT name FROM employees ORDER BY salary DESC;"],
    ["SELECT name FROM employees ORDER BY salary DESC;"],
]
task_data = [
    {
        "db": {
            "db_id": "mock_db",
            "db_type": "in_memory",
            "data": {
                "employees": {
                    "columns": ["id", "name", "department", "salary"],
                    "rows": [
                        (1, "Alice", "Sales", 50000),
                        (2, "Bob", "Engineering", 60000),
                        (3, "Charlie", "Sales", 55000),
                    ],
                }
            },
        }
    }
] * 8

instance_targets = [
    {
        "error_message": "Error executing SQL: no such column: nme",
        "execution_accuracy": 0,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 1,
        "predicted_df_json": "",
        "predicted_error": 1,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "",
        "execution_accuracy": 1,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 1,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "predicted_error": 0,
        "score": 1,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 1,
    },
    {
        "error_message": "",
        "execution_accuracy": 0,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Bob"}}',
        "predicted_error": 0,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "",
        "execution_accuracy": 0,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":1,"1":3},"1":{"0":"Alice","1":"Charlie"}}',
        "predicted_error": 0,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 1,
    },
    {
        "error_message": "",
        "execution_accuracy": 1,
        "gold_df_json": "{}",
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 0,
        "predicted_df_json": "{}",
        "predicted_error": 0,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "No SQL query found in the prediction.",
        "execution_accuracy": 0,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 1,
        "predicted_df_json": "",
        "predicted_error": 1,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "",
        "execution_accuracy": 0,
        "gold_df_json": '{"0":{"0":"Bob","1":"Charlie","2":"Alice"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Alice","1":"Charlie","2":"Bob"}}',
        "predicted_error": 0,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "",
        "execution_accuracy": 1,
        "gold_df_json": '{"0":{"0":"Bob","1":"Charlie","2":"Alice"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 1,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Bob","1":"Charlie","2":"Alice"}}',
        "predicted_error": 0,
        "score": 1,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 1,
    },
]

global_target = {
    "execution_accuracy": 0.38,
    "execution_accuracy_ci_high": 0.75,
    "execution_accuracy_ci_low": 0.12,
    "gold_error": 0.0,
    "gold_sql_runtime_ci_high": 0.0,
    "gold_sql_runtime_ci_low": 0.0,
    "non_empty_execution_accuracy": 0.25,
    "non_empty_execution_accuracy_ci_high": 0.62,
    "non_empty_execution_accuracy_ci_low": 0.0,
    "non_empty_gold_df": 0.88,
    "num_of_instances": 8,
    "predicted_error": 0.25,
    "predicted_sql_runtime_ci_high": 0.0,
    "predicted_sql_runtime_ci_low": 0.0,
    "score": 0.25,
    "score_ci_high": 0.62,
    "score_ci_low": 0.0,
    "score_name": "non_empty_execution_accuracy",
    "subset_non_empty_execution_accuracy": 0.38,
    "subset_non_empty_execution_accuracy_ci_high": 0.75,
    "subset_non_empty_execution_accuracy_ci_low": 0.12,
}

outputs = test_metric(
    metric=sql_execution_accuracy_metric,
    predictions=predictions,
    references=references,
    instance_targets=instance_targets,
    global_target=global_target,
    task_data=task_data,
    score_keys_to_ignore=[
        "predicted_sql_runtime",
        "gold_sql_runtime",
        "pred_to_gold_runtime_ratio",
    ],
)

add_to_catalog(
    sql_execution_accuracy_metric, "metrics.text2sql.execution_accuracy", overwrite=True
)

sql_non_execution_accuracy_metric = SQLNonExecutionAccuracy()

instance_targets = [
    {
        "score": 0,
        "score_name": "sqlglot_equivalence",
        "sql_exact_match": 0,
        "sqlglot_equivalence": 0,
        "sqlglot_optimized_equivalence": 0,
        "sqlglot_validity": 1,
        "sqlparse_equivalence": 0,
        "sql_syntactic_equivalence": 0,
        "sqlparse_validity": 1,
    },
    {
        "score": 1,
        "score_name": "sqlglot_equivalence",
        "sql_exact_match": 1,
        "sqlglot_equivalence": 1,
        "sqlglot_optimized_equivalence": 1,
        "sqlglot_validity": 1,
        "sqlparse_equivalence": 0,
        "sql_syntactic_equivalence": 1,
        "sqlparse_validity": 1,
    },
    {
        "score": 0,
        "score_name": "sqlglot_equivalence",
        "sql_exact_match": 0,
        "sqlglot_equivalence": 0,
        "sqlglot_optimized_equivalence": 0,
        "sqlglot_validity": 1,
        "sqlparse_equivalence": 0,
        "sql_syntactic_equivalence": 0,
        "sqlparse_validity": 1,
    },
    {
        "score": 0,
        "score_name": "sqlglot_equivalence",
        "sql_exact_match": 0,
        "sqlglot_equivalence": 0,
        "sqlglot_optimized_equivalence": 0,
        "sqlglot_validity": 1,
        "sqlparse_equivalence": 0,
        "sql_syntactic_equivalence": 0,
        "sqlparse_validity": 1,
    },
    {
        "score": 1,
        "score_name": "sqlglot_equivalence",
        "sql_exact_match": 1,
        "sqlglot_equivalence": 1,
        "sqlglot_optimized_equivalence": 1,
        "sqlglot_validity": 1,
        "sqlparse_equivalence": 0,
        "sql_syntactic_equivalence": 1,
        "sqlparse_validity": 1,
    },
    {
        "score": 0,
        "score_name": "sqlglot_equivalence",
        "sql_exact_match": 0,
        "sqlglot_equivalence": 0,
        "sqlglot_optimized_equivalence": 0,
        "sqlglot_validity": 0,
        "sqlparse_equivalence": 0,
        "sql_syntactic_equivalence": 0,
        "sqlparse_validity": 0,
    },
    {
        "score": 0,
        "score_name": "sqlglot_equivalence",
        "sql_exact_match": 0,
        "sqlglot_equivalence": 0,
        "sqlglot_optimized_equivalence": 0,
        "sqlglot_validity": 1,
        "sqlparse_equivalence": 0,
        "sql_syntactic_equivalence": 0,
        "sqlparse_validity": 1,
    },
    {
        "score": 1,
        "score_name": "sqlglot_equivalence",
        "sql_exact_match": 1,
        "sql_syntactic_equivalence": 1,
        "sqlglot_equivalence": 1,
        "sqlglot_optimized_equivalence": 1,
        "sqlglot_validity": 1,
        "sqlparse_equivalence": 1,
        "sqlparse_validity": 1,
    },
]


global_target = {
    "num_of_instances": 8,
    "score": 0.38,
    "score_ci_high": 0.75,
    "score_ci_low": 0.12,
    "score_name": "sqlglot_equivalence",
    "sql_exact_match": 0.38,
    "sql_exact_match_ci_high": 0.75,
    "sql_exact_match_ci_low": 0.12,
    "sql_syntactic_equivalence": 0.38,
    "sql_syntactic_equivalence_ci_high": 0.75,
    "sql_syntactic_equivalence_ci_low": 0.12,
    "sqlglot_equivalence": 0.38,
    "sqlglot_equivalence_ci_high": 0.75,
    "sqlglot_equivalence_ci_low": 0.12,
    "sqlglot_optimized_equivalence": 0.38,
    "sqlglot_optimized_equivalence_ci_high": 0.75,
    "sqlglot_optimized_equivalence_ci_low": 0.12,
    "sqlglot_validity": 0.88,
    "sqlglot_validity_ci_high": 1.0,
    "sqlglot_validity_ci_low": 0.5,
    "sqlparse_equivalence": 0.12,
    "sqlparse_equivalence_ci_high": 0.5,
    "sqlparse_equivalence_ci_low": 0.0,
    "sqlparse_validity": 0.88,
    "sqlparse_validity_ci_high": 1.0,
    "sqlparse_validity_ci_low": 0.5,
}

outputs = test_metric(
    metric=sql_non_execution_accuracy_metric,
    predictions=predictions,
    references=references,
    instance_targets=instance_targets,
    global_target=global_target,
    task_data=task_data,
)

add_to_catalog(
    sql_non_execution_accuracy_metric,
    "metrics.text2sql.non_execution_accuracy",
    overwrite=True,
)

sql_execution_logic_accuracy_metric = SQLExecutionLogicAccuracy()

instance_targets = [
    {
        "error_message": "",
        "execution_accuracy": 1,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 1,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "predicted_error": 0,
        "score": 1,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 1,
    },
    {
        "error_message": "",
        "execution_accuracy": 1,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 1,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "predicted_error": 0,
        "score": 1,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 1,
    },
    {
        "error_message": "",
        "execution_accuracy": 0,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Bob"}}',
        "predicted_error": 0,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "",
        "execution_accuracy": 1,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 1,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "predicted_error": 0,
        "score": 1,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 1,
    },
    {
        "error_message": "",
        "execution_accuracy": 1,
        "gold_df_json": "{}",
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 0,
        "predicted_df_json": "{}",
        "predicted_error": 0,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "No SQL query found in the prediction.",
        "execution_accuracy": 0,
        "gold_df_json": '{"0":{"0":"Alice","1":"Charlie"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 1,
        "predicted_df_json": "",
        "predicted_error": 1,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "",
        "execution_accuracy": 0,
        "gold_df_json": '{"0":{"0":"Bob","1":"Charlie","2":"Alice"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 0,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Alice","1":"Charlie","2":"Bob"}}',
        "predicted_error": 0,
        "score": 0,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 0,
    },
    {
        "error_message": "",
        "execution_accuracy": 1,
        "gold_df_json": '{"0":{"0":"Bob","1":"Charlie","2":"Alice"}}',
        "gold_error": 0,
        "non_empty_execution_accuracy": 1,
        "non_empty_gold_df": 1,
        "predicted_df_json": '{"0":{"0":"Bob","1":"Charlie","2":"Alice"}}',
        "predicted_error": 0,
        "score": 1,
        "score_name": "non_empty_execution_accuracy",
        "subset_non_empty_execution_accuracy": 1,
    },
]

global_target = {
    "execution_accuracy": 0.62,
    "execution_accuracy_ci_high": 0.88,
    "execution_accuracy_ci_low": 0.25,
    "gold_error": 0.0,
    "gold_sql_runtime_ci_high": 0.0,
    "gold_sql_runtime_ci_low": 0.0,
    "non_empty_execution_accuracy": 0.5,
    "non_empty_execution_accuracy_ci_high": 0.88,
    "non_empty_execution_accuracy_ci_low": 0.12,
    "non_empty_gold_df": 0.88,
    "num_of_instances": 8,
    "predicted_error": 0.12,
    "predicted_sql_runtime_ci_high": 0.0,
    "predicted_sql_runtime_ci_low": 0.0,
    "score": 0.5,
    "score_ci_high": 0.88,
    "score_ci_low": 0.12,
    "score_name": "non_empty_execution_accuracy",
    "subset_non_empty_execution_accuracy": 0.5,
    "subset_non_empty_execution_accuracy_ci_high": 0.88,
    "subset_non_empty_execution_accuracy_ci_low": 0.12,
}

outputs = test_metric(
    metric=sql_execution_logic_accuracy_metric,
    predictions=predictions,
    references=references,
    instance_targets=instance_targets,
    global_target=global_target,
    task_data=task_data,
    score_keys_to_ignore=[
        "predicted_sql_runtime",
        "gold_sql_runtime",
        "pred_to_gold_runtime_ratio",
    ],
)

add_to_catalog(
    sql_execution_accuracy_metric,
    "metrics.text2sql.execution_logic_accuracy",
    overwrite=True,
)
