#!/bin/sh

git fetch
git checkout main
export current_version=$(grep version src/unitxt/version.py |cut -d \" -f2)

echo "current_version=$current_version"
git tag $current_version
git push origin $current_version
