name: Test Docs Compilation

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-docs.yml
    cancel-in-progress: true

jobs:
    docs:

      runs-on: ubuntu-latest
      env:
        OS: ubuntu-latest
        PYTHONPATH: ./docs

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.9'

        - run: curl -LsSf https://astral.sh/uv/install.sh | sh
        - run: uv pip install --system ".[tests,docs]"

        - name: Compile Docs
          run: make docs


