name: Test Docs Compilation

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    compile-docs:

      runs-on: ubuntu-latest
      env:
        OS: ubuntu-latest
        PYTHONPATH: ./docs

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: curl -LsSf https://astral.sh/uv/install.sh | sh
        - run: uv pip install --system ".[tests,docs]"

        - name: Compile Docs
          run: make docs


