name: Test Docs Compilation

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    compile-docs:

      runs-on: ubuntu-latest
      env:
        OS: ubuntu-latest
        PYTHON: '3.8'

      steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ env.PYTHON }}
          cache: 'pip'

      - name: Install Requirements
        run: pip install .[docs,dev,base]

      - name: Compile Docs
        run: make docs


