name: Test Docs Compilation

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    compile-docs:

      runs-on: ubuntu-latest
      env:
        OS: ubuntu-latest
        PYTHON: '3.8'
        PYTHONPATH: ./docs

      steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.rqr') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          for file in requirements/*.rqr; do
            pip install -r $file
          done

      - name: Print Python Path
        run: python -c "import sys; print(sys.path)"

      - name: Compile Docs
        run: make docs


