name: Test Code Examples

on:
  pull_request:
    paths:
      - 'examples/*'
      - 'tests/examples/*.py'
      - '.github/workflows/examples_tests.yml'
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OS: ubuntu-latest
      UNITXT_DEFAULT_VERBOSITY: error
      DATASETS_VERBOSITY: error
      HF_HUB_VERBOSITY: error
      HF_DATASETS_DISABLE_PROGRESS_BARS: "True"
      HF_HUB_DOWNLOAD_TIMEOUT: 60
      HF_HUB_ETAG_TIMEOUT: 60
      TQDM_DISABLE: "True"
      WML_URL: ${{ secrets.WML_URL }}
      WML_PROJECT_ID: ${{ secrets.WML_PROJECT_ID }}
      WML_APIKEY: ${{ secrets.WML_APIKEY }}
      GENAI_KEY: ${{ secrets.GENAI_KEY }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: echo "blis==0" > constraints.txt
    - run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - run: uv pip install --upgrade --system torch --index-url https://download.pytorch.org/whl/cpu
    - run: uv pip install --system -c constraints.txt -e ".[tests]"
    - run: |
        pip install --only-binary :all: spacy
        pip install networkx==3.2.1

    - name: Install spacy (binary)
      run: |
        pip install --only-binary :all: spacy
        pip install networkx==3.2.1
        pip install datasets==3.5.1

    - name: Hugging Face Login
      run: |
        for i in {1..5}; do
          huggingface-cli login --token ${{ secrets.UNITXT_READ_HUGGINGFACE_HUB_FOR_TESTS }} && break || sleep $((2 ** i));
        done

    - name: Run Tests
      run: python -m unittest discover -s tests/examples -p "test_*.py"