name: Format code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install -r dev_requiremets.txt
      - name: Validate no fromat is needed
        run: |
          ./utils/format
      - name: Validate no fromat is needed
        run: |
          .github/workflows/validate_no_status_modifications