name: Test Inference Engines

on:
  pull_request:
    paths:
      - 'src/unitxt/inference.py'
      - 'tests/inference/*.py'
      - '.github/workflows/inference_tests.yml'

  release:
    types: [published]

jobs:
   run-full-tests-suit:

     runs-on: ubuntu-latest
     env:
       OS: ubuntu-latest
       UNITXT_DEFAULT_VERBOSITY: error
       DATASETS_VERBOSITY: error
       HF_HUB_VERBOSITY: error
       HF_DATASETS_DISABLE_PROGRESS_BARS: "True"
       TQDM_DISABLE: "True"
       WML_URL: ${{ secrets.WML_URL }}
       WML_PROJECT_ID: ${{ secrets.WML_PROJECT_ID }}
       WML_APIKEY: ${{ secrets.WML_APIKEY }}
       GENAI_KEY: ${{ secrets.GENAI_KEY }}

     steps:
     - uses: actions/checkout@v4

     - uses: actions/setup-python@v5
       with:
         python-version: '3.10'

     - run: curl -LsSf https://astral.sh/uv/install.sh | sh
     - run: uv pip install --system ".[tests,watsonx,inference-tests]"
     - run: huggingface-cli login --token ${{ secrets.UNITXT_READ_HUGGINGFACE_HUB_FOR_TESTS }}

     - name: Run Tests
       run: python -m unittest discover -s tests/inference -p "test_*.py"