name: Quality & Security Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-pre-commit-done:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install -r dev_requiremets.txt
      - name: Install the pre-commit hooks
        run: |
            pre-commit install
      - name: Validate all pre-commit verification were run correctly
        run: |
            pre-commit run --all-files


                
